# some of these settings are overridden in also test/.rubocop.yml

require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "node_modules/**/*"

Bundler/OrderedGems:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 50
  AllowedMethods:
    - concerning
    - context
    - should

Metrics/BlockNesting:
  CountBlocks: false
  Max: 4

Metrics/ClassLength:
  Max: 500

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 100

Metrics/ModuleLength:
  Max: 500

Metrics/ParameterLists:
  Max: 6

Metrics/PerceivedComplexity:
  Max: 20

Lint/InheritException:
  EnforcedStyle: standard_error

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Rails/Blank:
  UnlessPresent: false

Rails/DynamicFindBy:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/HttpStatus:
  EnforcedStyle: numeric

Rails/InverseOf:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FloatDivision:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 20

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "default": "{}"
    "%i": "[]"
    "%I": "[]"
    "%w": "[]"
    "%W": "[]"
    "%r": "{}"

Style/ParallelAssignment:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed
  AllowInnerSlashes: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SymbolArray:
  MinSize: 10

Style/SymbolProc:
  AllowedMethods:
    - respond_with

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/WordArray:
  MinSize: 10
