# Deploy the site to https://beta.aibooru.online on every push to the `beta` branch.

name: Deploy Betabooru

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
permissions: read-all

on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run
  workflow_dispatch:
  workflow_run:
    workflows: [Docker Build]
    types: [completed]
    branches: [beta]

jobs:
  deploy-betabooru:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
    concurrency: deploy-betabooru

    # The Kubernetes API credentials are kept in the betabooru environment.
    # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idenvironment
    environment:
      name: beta
      url: https://beta.aibooru.online

    steps:
    # https://github.com/marketplace/actions/kubectl-tool-installer
    - name: Install Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.21.5

    - name: Configure Kubectl
      run: |
        mkdir -p ~/.kube
        echo "$KUBECONFIG_YAML" > ~/.kube/config
      env:
        KUBECONFIG_YAML: ${{secrets.KUBECONFIG_YAML}}

    - name: Deploy to Betabooru
      run: |
        kubectl rollout restart deploy/betabooru -n danbooru
